#!/usr/bin/env node
/**
 * `npm run check` — the mechanical checks this project can run in one command.
 *
 * Zero dependencies (CLAUDE.md: no new packages) and no shell, so it behaves the same in
 * PowerShell, bash and CI. It covers SPEC Block H checks 5 and 6, plus the mechanical
 * form of rules 3b, 5 and 7 — every notes query goes through the DAL and filters by
 * `user_id`. That last one is the highest-value guard this project can automate, because
 * dropping an ownership filter would still typecheck, still build, and still pass every
 * other gate. It does NOT cover all of Block H: check 1 is `typecheck`/`build`, checks
 * 2-4 and 7 are browser and dashboard work, and check 9 needs the network.
 *
 * WHAT THIS CANNOT DO, stated so nobody mistakes green for proof: it reads text. It can
 * see that `.eq("user_id", user.id)` sits inside a query chain; it cannot see whether
 * that chain is the one a page actually calls, or whether RLS is still enabled on the
 * live table. The second one is the real gap — nothing in this repo re-verifies the live
 * database, and it is recorded as post-sprint debt (SPEC, the `check:live` probe). Those
 * are review questions (`.claude/commands/review-auth.md`) and dashboard checks, and this
 * script is not a substitute for either.
 *
 * Hardened at the Phase 7 /full-review, where mutation testing defeated five of these
 * checks. Every fix below carries the case it closes, because a check whose bypass is
 * undocumented gets loosened by the next person who trips over it.
 */
import { readFileSync, readdirSync, statSync, existsSync } from "node:fs";
import { join, relative, sep } from "node:path";

// Anchored to THIS FILE, not to the caller. With `process.cwd()`, a run from any other
// directory found no files and reported seven vacuous PASSes; only the two checks with
// hardcoded paths failed, and then only by throwing ENOENT. A guard that passes when it
// scanned nothing is worse than no guard, because it is trusted.
const ROOT = join(import.meta.dirname, "..");
const CODE_DIRS = ["app", "components", "lib"];
const CODE_FILES = ["proxy.ts"];
// `.js`/`.jsx` matter even though none exist today: Next's default `pageExtensions`
// routes them and `tsconfig.json` sets `allowJs: false`, so a .jsx page would ship while
// escaping BOTH this script and `npm run typecheck`. A mutation test put web storage, a
// service-role read, an unfiltered query and an email literal in one .jsx file, and every
// gate stayed green.
const CODE_EXT = [".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"];
const ROOT_SKIP = ["next-env.d.ts"]; // regenerated by `next dev`, gitignored, not ours

/** Configured paths that do not exist. Fatal — see the preflight at the bottom. */
const missing = [];

/** Every code file under the given dirs/files, as repo-relative posix paths. */
function collect(dirs, files, exts) {
  const out = [];
  const walk = (dir) => {
    for (const entry of readdirSync(dir)) {
      const full = join(dir, entry);
      if (statSync(full).isDirectory()) walk(full);
      else if (exts.some((e) => entry.endsWith(e))) out.push(full);
    }
  };
  for (const d of dirs) {
    // A CONFIGURED directory that is absent is a failure, not a skip: renaming
    // `components/` to `app/_components/` would otherwise halve the coverage of every
    // text check while all of them still reported PASS.
    if (existsSync(join(ROOT, d))) walk(join(ROOT, d));
    else missing.push(d + "/");
  }
  for (const f of files) {
    if (existsSync(join(ROOT, f))) out.push(join(ROOT, f));
    else missing.push(f);
  }
  return out.map((p) => relative(ROOT, p).split(sep).join("/"));
}

const CODE = collect(CODE_DIRS, CODE_FILES, CODE_EXT);
const SQL = collect(["supabase"], [], [".sql"]);

// Block H check 5 scans WIDER than the app-code checks below it. The two prohibitions it
// carries — no web storage, no service-role key — have to hold for every line of code
// this repo ships, not just the ones that render a page: build config and these scripts
// can read an env var and reach Supabase just as easily. Narrowing check 5 to app code
// was a coverage regression against the old unscoped `grep -ri . `, introduced by the
// very commit that added this directory.
//
// `.env.example` is included BY NAME. It is the committed env template, and the most
// plausible place for a key to be pasted. `.env.local` and any `.env*` glob are
// deliberately NOT scanned: printing a finding out of a real secrets file would leak the
// secret, which is the same reasoning that keeps WORKLOG.md out of scope (rule 19).
const ROOT_CODE = readdirSync(ROOT).filter(
  (f) =>
    CODE_EXT.some((e) => f.endsWith(e)) &&
    !ROOT_SKIP.includes(f) &&
    statSync(join(ROOT, f)).isFile(),
);
const WIDE = [
  ...new Set([
    ...CODE,
    ...collect(["scripts"], ROOT_CODE, CODE_EXT),
    ...(existsSync(join(ROOT, ".env.example")) ? [".env.example"] : []),
  ]),
];

// Both needles are ASSEMBLED FROM FRAGMENTS rather than written out, and that is
// load-bearing: this file is inside the scope it scans, so a literal needle here would
// match itself and fail the check it implements. It has to cover the CONSTANT NAMES too —
// an identifier named after the key matched the case-insensitive needle just as well as a
// string does, and then so did the comment explaining the trick. Both happened.
const WEB_STORAGE = new RegExp("local" + "Storage|" + "session" + "Storage", "i");
// FOUR spellings, not one, and the extra three are why this check still means anything.
// The legacy service-role name was the whole needle until the security audit on
// lab/agents, which found it one key GENERATION behind the key this project actually
// uses: an `sb_publishable_` key is paired with a secret key whose name shares NO
// substring with the legacy one, and whose conventional variable name is the third
// fragment below. A new-format secret key pasted into .env.example — the most plausible
// place for it — passed every gate green. The fourth fragment is the same failure one
// generation earlier: a hand-shortened legacy name.
//
// Note the phrasing above, and keep it: this comment cannot SPELL the strings it is about
// without matching itself, which is the trap the paragraph above already records. Say
// "the legacy service-role name", never the underscored form.
const PRIVILEGED_KEY = new RegExp(
  ["service" + "_role", "sb" + "_secret_", "SECRET" + "_KEY", "SERVICE" + "_KEY"].join("|"),
  "i",
);

// The OpenRouter key, in the two shapes that put it in a browser bundle. Fragments again,
// and for the same reason the paragraph above gives: both needles would otherwise match
// their own source line.
//
// This is the MIRROR of the check above, not a copy of it. PRIVILEGED_KEY hunts a value
// that must never be public and whose variable IS public by design (NEXT_PUBLIC_SUPABASE_*
// exists and is correct); this one hunts a value that must never be public and whose
// variable is correctly named OPENROUTER_API_KEY with no prefix at all. So the finding here
// is not the key's name on its own — it is the PUBLIC PREFIX attached to it.
//
// Two spellings, because they fail differently. A name a developer wrote on purpose
// (`NEXT_PUBLIC_` + this key's name) is the honest mistake — someone hit the "why is this
// undefined in the browser" wall and fixed it the way that makes the error go away. A raw
// key LITERAL is the careless one: pasted into a component to test something, then
// committed. Neither is caught by the checks above, and both ship a working, billable
// credential to anyone who views source.
const PUBLIC_OPENROUTER = new RegExp("NEXT" + "_PUBLIC_[A-Z0-9_]*OPEN" + "ROUTER", "i");
const OPENROUTER_KEY_LITERAL = new RegExp("sk" + "-or-", "i");

// Any quoting of the table name, and any whitespace. This matched `"notes"` only until
// the /full-review: `.from('notes')` slipped straight past it, and nothing in this repo
// pins quote style — there is no ESLint and no Prettier config.
const tableFromSrc = (table) => '\\.from\\(\\s*["\'`]' + table + '["\'`]\\s*\\)';

// EVERY TABLE AND ITS ONE DAL. Both checks below are driven by this list rather than by a
// hardcoded `lib/notes.ts`, and that is the whole reason it exists: the chat persistence
// amendment added a SECOND table, and a chokepoint check that knew about only the first
// would have reported PASS while the new table was reachable from anywhere in the app.
// The rule is one door per table (CLAUDE.md rule 3b), so adding a table means adding a
// line here — and forgetting to is a FAIL rather than a silent gap, because `.from(`
// anything, in any file that is not a listed DAL, is already a finding.
//
// Adding a row weakens nothing. Each DAL is still required to carry the ownership filter
// on every one of its own query chains, still checked statement by statement, and still
// required to contain at least one query at all.
const DALS = [
  { dal: "lib/notes.ts", table: "notes" },
  { dal: "lib/chatMessages.ts", table: "chat_messages" },
];
const DAL_FILES = DALS.map((entry) => entry.dal);
// Outside the DAL, ANY table access is a finding — including one whose argument is not a
// literal (`.from(table)`), which cannot be cleared by reading text. `Array.from`,
// `Buffer.from` and `Object.from` are the standard-library uses that would otherwise
// match; `Array.from` is used twice in components/Skeletons.tsx.
const OPAQUE_FROM = /(?<!Array)(?<!Buffer)(?<!Object)\.from\(/;
// The ownership filter must name `user.id` literally. `.eq("user_id", patch.ownerId ??
// user.id)` passed the old pattern — which is exactly the rule-3b violation review
// question 9 asks about: a user id arriving from the client.
const OWNED_BY_FILTER = /\.eq\(\s*["'`]user_id["'`]\s*,\s*user\.id\s*\)/;
const OWNED_BY_INSERT = /user_id:\s*user\.id/;

const read = (p) => readFileSync(join(ROOT, p), "utf8");

/**
 * Comments blanked, offsets preserved.
 *
 * Needed because these checks read raw text: deleting an ownership filter and leaving
 * `// RLS already scopes this, so .eq("user_id", user.id) is redundant` — a comment in
 * exactly the register this codebase writes in — made the rule-7 check report PASS on a
 * query that had no filter at all. Newlines are kept, so reported line numbers stay true.
 *
 * Honest limit: this is a blanker, not a parser. A `//` inside a string literal would
 * blank the rest of that line. Verified at the /full-review that no scanned file has one
 * (no URL literals in app code), and a false FAIL is the safe direction anyway.
 */
function blankComments(src) {
  return src
    .replace(/\/\*[\s\S]*?\*\//g, (m) => m.replace(/[^\n]/g, " "))
    .replace(/\/\/[^\n]*/g, (m) => " ".repeat(m.length));
}

/**
 * The same, for SQL: `--` to end of line, plus block comments.
 *
 * A separate function because blankComments() does not know `--`, and the two SQL checks
 * below would otherwise fail on the comments that EXPLAIN them: supabase/schema.sql now
 * carries a note about why its one function spells out its security mode, and such a note
 * cannot avoid naming the mode it is not. Exactly the lesson blankComments() was written
 * for — a comment in the register this codebase writes in defeated the rule-7 check.
 * Offsets and newlines are preserved, so reported line numbers stay true.
 *
 * Honest limit, same as its sibling: a blanker, not a parser. A `--` inside a string
 * literal or a dollar-quoted body would blank the rest of that line. No file in
 * supabase/ has one, and a false FAIL is the safe direction anyway.
 */
function blankSqlComments(src) {
  return src
    .replace(/\/\*[\s\S]*?\*\//g, (m) => m.replace(/[^\n]/g, " "))
    .replace(/--[^\n]*/g, (m) => " ".repeat(m.length));
}

/** Every line matching `re`, as "path:line: text" — the failure detail. */
function hits(paths, re, { stripComments = false } = {}) {
  const found = [];
  for (const p of paths) {
    const src = stripComments ? blankComments(read(p)) : read(p);
    src.split(/\r?\n/).forEach((line, i) => {
      if (re.test(line)) found.push(`${p}:${i + 1}: ${line.trim().slice(0, 100)}`);
    });
  }
  return found;
}

const checks = [];
const check = (name, why, fn) => checks.push({ name, why, fn });

// ── Block H check 5, first grep ────────────────────────────────────────────────
check(
  "no web storage",
  "rule 6 — Supabase is the only persistence layer, for notes and for the session",
  () => hits(WIDE, WEB_STORAGE),
);

// ── Block H check 5, second grep, widened at the security audit to all four spellings
//    of the privileged key. Every code file the repo ships — app/, components/,
//    lib/, proxy.ts, next.config.ts, postcss.config.mjs, scripts/, .env.example, plus
//    supabase/. Prose about the key is not a use of it, so .agents/skills/, .claude/,
//    docs/, SPEC.md, WORKLOG.md and .next/ stay out of scope by design (SPEC Block H
//    check 5 names the known prose hits). ────────────────────────────────────────
check(
  "no privileged key, under any of its names",
  "rule 4 — this project needs only the low-privilege key, and the privileged one has had two names",
  () => hits([...WIDE, ...SQL], PRIVILEGED_KEY),
);

// ── The OpenRouter key stays on the server. Same WIDE scope as check 5 above, and for
//    the same reason: build config and these scripts can read an env var and reach a
//    model host just as easily as a page can. Both modules in lib/openrouter/ carry a
//    `server-only` import, which is the stronger fence — it fails the BUILD if a Client
//    Component imports either — but it only guards those two files. It says nothing about
//    a key pasted into a component directly, or read from a NEXT_PUBLIC_ name somewhere
//    else, which is what this reads text to find. ─────────────────────────────────────
check(
  "no OpenRouter key exposed to the browser",
  'CLAUDE.md "AI model calls" — server-side only; every NEXT_PUBLIC_* value is inlined into the browser bundle',
  () => [
    ...hits([...WIDE, ...SQL], PUBLIC_OPENROUTER),
    ...hits([...WIDE, ...SQL], OPENROUTER_KEY_LITERAL),
  ],
);

// ── Block H check 6. Matches a CALL (`.getSession(`), not the many comments that
//    name `getSession()` to explain why it is never called. ────────────────────
check(
  "no getSession() call sites",
  "rule 2 — getSession() does not validate the token, so it cannot decide access",
  () => hits(CODE, /\.getSession\s*\(/, { stripComments: true }),
);

// ── rule 3b: one chokepoint for notes data ────────────────────────────────────
check(
  "every table query lives in its DAL",
  "rule 3b — no page, component or Server Action touches a table directly",
  () => {
    const outside = CODE.filter((p) => !DAL_FILES.includes(p));
    return [
      ...hits(outside, OPAQUE_FROM, { stripComments: true }),
      // `.rpc()` is the other entry point into the same table — lib/notes.ts names it as
      // such where it explains why listTags does not use one.
      ...hits(outside, /\.rpc\(/, { stripComments: true }),
    ];
  },
);

// ── rule 7, mechanically: each query chain carries the ownership filter ────────
check(
  "every table query filters by user_id",
  "rule 7 — the explicit filter is mandatory even with RLS enabled",
  () => {
    const bad = [];
    // Every DAL, not only the notes one — and run per FILE, so a chain in one module can
    // never be cleared by a filter written in another.
    for (const { dal, table } of DALS) {
      const src = blankComments(read(dal));
      const FROM_SRC = tableFromSrc(table);
      const FROM = new RegExp(FROM_SRC);
      let seen = 0;
      // Scoped to the STATEMENT, not to a window of lines. A fixed window is fooled by
      // the next query's filter when two chains sit close together — a broken chain then
      // borrows its neighbour's `.eq("user_id", …)` and the check passes.
      const scanner = new RegExp(FROM_SRC, "g");
      for (let m = scanner.exec(src); m; m = scanner.exec(src)) {
        seen += 1;
        const line = src.slice(0, m.index).split("\n").length;
        const rest = src.slice(m.index + m[0].length);
        const semi = rest.indexOf(";");
        // A fresh non-global regex: `.search()` with the `g`-flagged scanner would move
        // its `lastIndex` and make the outer loop skip matches.
        const next = rest.search(FROM);
        // An UNTERMINATED chain FAILS rather than opening the window to end of file. That
        // fallback let a query with no filter borrow one written anywhere later in the
        // module, so a missing `;` was enough to turn this check green.
        if (semi < 0 || (next >= 0 && next < semi)) {
          bad.push(
            `${dal}:${line}: query chain has no terminating ';' — cannot bound it`,
          );
          continue;
        }
        const chain = rest.slice(0, semi);
        if (!OWNED_BY_FILTER.test(chain) && !OWNED_BY_INSERT.test(chain)) {
          bad.push(`${dal}:${line}: no .eq("user_id", user.id) in this chain`);
        }
      }
      if (seen === 0) {
        bad.push(`${dal}: no ${table} query found at all — has the DAL moved?`);
      }
    }
    return bad;
  },
);

// ── The phantom-dialog regression, guarded by one line ────────────────────────
//    Honest scope, restated after the /full-review: this pins the DECLARATION. It cannot
//    see `className={`${DIALOG_CLASS} flex`}` at the call site, which reintroduces the
//    original bug — that is what BUILD_PHASES Phase 4 probe 2 is for.
check(
  "the dialog spells out both states",
  "a closed <dialog> painted over the editor once, with its Delete armed — the fix is that both `hidden` and `open:flex` are present",
  () => {
    const src = read("components/ConfirmDialog.tsx");
    const decl = src.match(/const DIALOG_CLASS\s*=\s*["'`]([^"'`]*)["'`]/);
    if (!decl) {
      return [
        "components/ConfirmDialog.tsx: could not parse DIALOG_CLASS — has its shape changed?",
      ];
    }
    const absent = ["hidden", "open:flex"].filter(
      (c) => !decl[1].split(/\s+/).includes(c),
    );
    return absent.map(
      (c) => `components/ConfirmDialog.tsx: DIALOG_CLASS is missing \`${c}\``,
    );
  },
);

// ── Two prohibitions from SPEC Block A / rule 5 ───────────────────────────────
check(
  "no dangerouslySetInnerHTML",
  "SPEC Block A — prohibited outright (it is also why no copy string is ever HTML)",
  () => hits(CODE, /dangerouslySetInnerHTML\s*[=:]/, { stripComments: true }),
);
check(
  "no hardcoded email addresses",
  "rule 5 — no address literal anywhere in the code",
  // WIDE, not CODE: rule 5 says anywhere in the code, and scripts/ and build config are
  // code too.
  () =>
    hits(WIDE, /[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/, {
      stripComments: true,
    }),
);

// ── The two ways a schema hands out an RLS bypass (security audit, S3) ─────────
//    Both are SQL-only, and this repo has ZERO of either today — these checks exist to
//    keep that true, because each is one line that silently moves the fence. Not Block H
//    checks: they automate two things the audit had to establish by reading the schema.
check(
  "no SECURITY DEFINER in supabase/",
  "a definer-rights function runs as its OWNER, so it reads and writes rows the caller's RLS policies would refuse — the standard way RLS is bypassed after the fact",
  () => {
    const bad = [];
    for (const path of SQL) {
      blankSqlComments(read(path))
        .split(/\r?\n/)
        .forEach((line, i) => {
          if (/security\s+definer/i.test(line)) {
            bad.push(`${path}:${i + 1}: ${line.trim().slice(0, 100)}`);
          }
        });
    }
    return bad;
  },
);

check(
  "every view in supabase/ sets security_invoker",
  "a view created without it runs with its OWNER's rights, so selecting from it returns rows the caller's RLS policies would refuse — Postgres defaults this OFF",
  () => {
    const bad = [];
    // Statement-bounded, like the rule-7 check: `create view` and the `with (…)` clause
    // that would clear it are routinely on different lines, so no per-line test can.
    for (const path of SQL) {
      const src = blankSqlComments(read(path));
      const scanner = /create\s+(?:or\s+replace\s+)?(?:materialized\s+)?view\s+([^\s(]+)/gi;
      for (let m = scanner.exec(src); m; m = scanner.exec(src)) {
        const line = src.slice(0, m.index).split("\n").length;
        const semi = src.slice(m.index).indexOf(";");
        // An unterminated statement FAILS rather than opening the window to end of file —
        // the same reasoning as the rule-7 chain check, where that fallback let a query
        // borrow a filter written anywhere later in the module.
        if (semi < 0) {
          bad.push(`${path}:${line}: view ${m[1]} — no terminating ';', cannot bound it`);
          continue;
        }
        const stmt = src.slice(m.index, m.index + semi);
        if (!/security_invoker\s*=\s*(?:true|on)/i.test(stmt)) {
          bad.push(`${path}:${line}: view ${m[1]} does not set security_invoker = true`);
        }
      }
    }
    return bad;
  },
);

// ── App Router only ───────────────────────────────────────────────────────────
check(
  "no pages/ directory",
  "SPEC Block A — App Router only; a stray pages/ dir changes routing silently",
  () => (existsSync(join(ROOT, "pages")) ? ["pages/ exists"] : []),
);

// ── Preflight, then the checks ─────────────────────────────────────────────────
// A configured path that has moved makes every text check weaker without making any of
// them fail, so it is fatal on its own and reported before anything runs.
if (missing.length > 0) {
  console.error(`configured paths are missing: ${missing.join(", ")}`);
  console.error("fix the lists at the top of scripts/check.mjs, or restore the paths.");
  process.exitCode = 2;
} else if (CODE.length === 0 || SQL.length === 0 || WIDE.length === 0) {
  console.error(
    `scanned nothing (code=${CODE.length} wide=${WIDE.length} sql=${SQL.length}) — wrong root?`,
  );
  process.exitCode = 2;
} else {
  let failed = 0;
  console.log(
    `checking ${CODE.length} app files, ${WIDE.length} in the wider check-5 scope, ` +
      `and ${SQL.length} sql files\n`,
  );
  for (const { name, why, fn } of checks) {
    let found;
    try {
      found = fn();
    } catch (error) {
      found = [`check itself threw: ${error.message}`];
    }
    if (found.length === 0) {
      console.log(`  PASS  ${name}`);
    } else {
      failed += 1;
      // Findings to stderr, so a CI step can separate them from the progress log.
      console.error(`  FAIL  ${name}`);
      console.error(`        ${why}`);
      for (const line of found) console.error(`        ${line}`);
    }
  }
  console.log(
    `\n${checks.length - failed}/${checks.length} passed` +
      (failed ? " — see the lines above\n" : "\n"),
  );
  // `process.exitCode`, not `process.exit()`, so buffered stdout drains first.
  process.exitCode = failed === 0 ? 0 : 1;
}
